version: "3.9"

services:
  chatgpt_demo:
    image: zullq86w/chatgpt_demo:latest
    container_name: chatgpt_demo
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .env:/app/.env
