"""update_robot

Revision ID: cf9d2fcc1aa8
Revises: 95d758231045
Create Date: 2025-10-25 15:46:45.177790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf9d2fcc1aa8'
down_revision: Union[str, Sequence[str], None] = '95d758231045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_robots', sa.Column('keywords', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_robots', 'keywords')
    # ### end Alembic commands ###
